
name: Python CI

# Run only when committing to main
on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

  workflow_dispatch:
jobs:
  # 1st Job: Build
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout commit
      - uses: actions/checkout@v2

      # Setup python 3.9.1 environment
      - name: Set up Python 3.9.1
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'

      # Install specific version of modules to build and run
      - name: Install modules      
        run: |
          pip install -r requirements.txt
          pip install -r build_requirements.txt

      # Create one-file executable for both the server and client
      - name: Create executable using pyinstaller
        run: |
          pyinstaller --onefile --add-data "names.txt:." client.py
          pyinstaller --onefile --add-data "names.txt:." server.py

      # Upload two executables into artifact for release job
      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: pyinstaller_dist
          path: ./dist
      - name: Upload names.txt
        uses: actions/upload-artifact@v2.2.3
        with:
          name: names
          path: ./names.txt
  # 2nd Job: Release (depends on build)   
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Create a public release 
      - name: Create release
        uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: "v0.${{ github.run_number }}"
          release_name: "Release v0.${{ github.run_number }}"
          draft: false
          prerelease: true
          body: "Executables for Socket-Squares"

      # Download/open artifact made in build job
      - name: Download artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: pyinstaller_dist
          
      - name: Download artifact 2
        uses: actions/download-artifact@v2.0.9
        with:
          name: names

      # Upload server.exe to release
      - name: Upload server.exe
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: server
          asset_name: socketsquares_server.exe
          asset_content_type: application/exe

      # Upload client.exe to release
      - name: Upload client.exe
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: client
          asset_name: socketsquares_client.exe
          asset_content_type: application/exe
          
      # Upload client.exe to release
      - name: Upload names.txt
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: names.txt
          asset_name: names.txt
          asset_content_type: application/txt
          
